import { useEffect, useMemo, useState } from "react";
import { Copy, MoreHorizontal, Plus, Save, Trash2, Utensils, X, Replace, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";

type Student = { id: string; full_name: string | null };
type Diet = { id: string; student_id: string; name: string; daily_calories: number | null; protein_g: number | null; carbs_g: number | null; fats_g: number | null; water_liters: number | null; notes: string | null; status: string };
type Meal = { id: string; diet_id: string; name: string; scheduled_time: string | null; position: number; notes: string | null };
type Item = { id: string; meal_id: string; food_id: string | null; food_name: string; quantity: number; unit: string; calories: number | null; protein_g: number | null; carbs_g: number | null; fats_g: number | null; position: number };
type Food = { id: string; name: string; calories_per_100g: number; protein_per_100g: number; carbs_per_100g: number; fats_per_100g: number; fiber_per_100g: number };
type Template = { id: string; name: string; description: string | null; goal: string | null; daily_calories: number | null; protein_g: number | null; carbs_g: number | null; fats_g: number | null };
type Substitution = { id: string; meal_item_id: string; food_id: string | null; food_name: string; quantity: number; unit: string; calories: number | null; protein_g: number | null; carbs_g: number | null; fats_g: number | null };

const db = supabase as any;
const blankFood = { name: "", calories_per_100g: 0, protein_per_100g: 0, carbs_per_100g: 0, fats_per_100g: 0, fiber_per_100g: 0 };
function calc(food: Pick<Food, "calories_per_100g" | "protein_per_100g" | "carbs_per_100g" | "fats_per_100g">, quantity: number) { const f = quantity / 100; return { calories: Math.round(food.calories_per_100g * f), protein_g: +(food.protein_per_100g * f).toFixed(1), carbs_g: +(food.carbs_per_100g * f).toFixed(1), fats_g: +(food.fats_per_100g * f).toFixed(1) }; }

export function DietModule() {
  const [view, setView] = useState<"diets" | "templates">("diets");
  const [students, setStudents] = useState<Student[]>([]); const [selectedStudent, setSelectedStudent] = useState("");
  const [diets, setDiets] = useState<Diet[]>([]); const [selectedDiet, setSelectedDiet] = useState<Diet | null>(null);
  const [meals, setMeals] = useState<Meal[]>([]); const [items, setItems] = useState<Record<string, Item[]>>({}); const [foods, setFoods] = useState<Food[]>([]);
  const [templates, setTemplates] = useState<Template[]>([]); const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null); const [templateMeals, setTemplateMeals] = useState<Meal[]>([]); const [templateItems, setTemplateItems] = useState<Record<string, Item[]>>({});
  const [dietOpen, setDietOpen] = useState(false); const [mealOpen, setMealOpen] = useState(false); const [foodOpen, setFoodOpen] = useState(false); const [templateOpen, setTemplateOpen] = useState(false); const [subOpen, setSubOpen] = useState(false); const [editItemOpen, setEditItemOpen] = useState(false);
  const [dietName, setDietName] = useState(""); const [dietNotes, setDietNotes] = useState(""); const [mealName, setMealName] = useState(""); const [mealTime, setMealTime] = useState(""); const [templateName, setTemplateName] = useState(""); const [templateDesc, setTemplateDesc] = useState("");
  const [foodForm, setFoodForm] = useState(blankFood); const [quantity, setQuantity] = useState(100); const [selectedMeal, setSelectedMeal] = useState<Meal | null>(null); const [selectedFoodId, setSelectedFoodId] = useState(""); const [editingItem, setEditingItem] = useState<Item | null>(null); const [substitutions, setSubstitutions] = useState<Substitution[]>([]); const [subFoodId, setSubFoodId] = useState(""); const [subQty, setSubQty] = useState(100);
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const allItems = useMemo(() => Object.values(items).flat(), [items]); const totals = useMemo(() => allItems.reduce((a,i)=>({calories:a.calories+(i.calories||0),protein:a.protein+(i.protein_g||0),carbs:a.carbs+(i.carbs_g||0),fats:a.fats+(i.fats_g||0)}),{calories:0,protein:0,carbs:0,fats:0}),[allItems]);

  async function loadStudents(){const {data,error}=await supabase.from("students").select("id,full_name").eq("status","ativo").order("full_name");if(error)setError(error.message);else{setStudents((data||[]) as Student[]);if(!selectedStudent&&data?.[0])setSelectedStudent(data[0].id);}}
  async function loadFoods(){const {data,error}=await db.from("foods").select("*").eq("active",true).order("name");if(error)setError(error.message);else setFoods((data||[]) as Food[]);}
  async function loadDiets(studentId=selectedStudent){if(!studentId){setDiets([]);setSelectedDiet(null);return;}const {data,error}=await supabase.from("diets").select("*").eq("student_id",studentId).order("created_at",{ascending:false});if(error)setError(error.message);else setDiets((data||[]) as Diet[]);}
  async function loadDiet(d:Diet){setSelectedDiet(d);const {data:ms,error}=await supabase.from("meals").select("*").eq("diet_id",d.id).order("position");if(error){setError(error.message);return;}setMeals((ms||[]) as Meal[]);const next:Record<string,Item[]>={};for(const m of (ms||[]) as Meal[]){const {data}=await db.from("meal_items").select("*").eq("meal_id",m.id).order("position");next[m.id]=(data||[]) as Item[];}setItems(next);}
  async function loadTemplates(){const {data,error}=await db.from("diet_templates").select("*").order("name");if(error)setError(error.message);else setTemplates((data||[]) as Template[]);}
  async function loadTemplate(t:Template){setSelectedTemplate(t);const {data:ms,error}=await db.from("diet_template_meals").select("*").eq("template_id",t.id).order("position");if(error){setError(error.message);return;}setTemplateMeals((ms||[]) as Meal[]);const next:Record<string,Item[]>={};for(const m of (ms||[]) as Meal[]){const {data}=await db.from("diet_template_items").select("*").eq("template_meal_id",m.id).order("position");next[m.id]=(data||[]) as Item[];}setTemplateItems(next);}
  useEffect(()=>{void loadStudents();void loadFoods();void loadTemplates();},[]); useEffect(()=>{void loadDiets();},[selectedStudent]);

  async function createDiet(){if(!selectedStudent||!dietName.trim())return;setSaving(true);const {data:user}=await supabase.auth.getUser();if(!user.user){setError("Faça login como personal.");setSaving(false);return;}const {data,error}=await supabase.from("diets").insert({student_id:selectedStudent,personal_id:user.user.id,name:dietName.trim(),notes:dietNotes.trim()||null,daily_calories:0,protein_g:0,carbs_g:0,fats_g:0}).select().single();if(error)setError(error.message);else{setDietOpen(false);setDietName("");setDietNotes("");await loadDiets();if(data)await loadDiet(data as Diet);}setSaving(false);}
  async function createMeal(){if(!selectedDiet||!mealName.trim())return;setSaving(true);const {data,error}=await supabase.from("meals").insert({diet_id:selectedDiet.id,name:mealName.trim(),scheduled_time:mealTime||null,position:meals.length}).select().single();if(error)setError(error.message);else{setMealOpen(false);setMealName("");setMealTime("");await loadDiet(selectedDiet);if(data)setSelectedMeal(data as Meal);}setSaving(false);}
  function chooseFood(id:string){setSelectedFoodId(id);const f=foods.find(x=>x.id===id);if(f)setFoodForm({...f});}
  async function saveFoodAndAdd(){if(!selectedMeal||!foodForm.name.trim())return;setSaving(true);const {data:user}=await supabase.auth.getUser();if(!user.user){setError("Faça login como personal.");setSaving(false);return;}let foodId=selectedFoodId||null;if(!foodId){const {data:created,error}=await db.from("foods").insert({personal_id:user.user.id,...foodForm}).select().single();if(error){setError(error.message);setSaving(false);return;}foodId=created.id;setFoods(c=>[...c,created as Food].sort((a,b)=>a.name.localeCompare(b.name)));}const macros=calc(foodForm,Number(quantity)||0);const {error}=await db.from("meal_items").insert({meal_id:selectedMeal.id,food_id:foodId,food_name:foodForm.name.trim(),quantity:Number(quantity),unit:"g",...macros,position:items[selectedMeal.id]?.length||0});if(error)setError(error.message);else{setFoodOpen(false);resetFood();await loadDiet(selectedDiet!);}setSaving(false);}
  function resetFood(){setFoodForm(blankFood);setSelectedFoodId("");setQuantity(100);}
  async function updateItem(){if(!editingItem)return;const food=foods.find(f=>f.id===editingItem.food_id);if(!food){setError("Alimento base não encontrado.");return;}const macros=calc(food,Number(quantity));const {error}=await db.from("meal_items").update({quantity:Number(quantity),...macros}).eq("id",editingItem.id);if(error)setError(error.message);else{setEditItemOpen(false);if(selectedDiet)await loadDiet(selectedDiet);}}
  async function removeItem(item:Item){const {error}=await db.from("meal_items").delete().eq("id",item.id);if(error)setError(error.message);else if(selectedDiet)await loadDiet(selectedDiet);}
  async function removeMeal(m:Meal){const {error}=await supabase.from("meals").delete().eq("id",m.id);if(error)setError(error.message);else if(selectedDiet)await loadDiet(selectedDiet);}
  async function syncTotals(){if(!selectedDiet)return;const {error}=await supabase.from("diets").update({daily_calories:totals.calories,protein_g:+totals.protein.toFixed(1),carbs_g:+totals.carbs.toFixed(1),fats_g:+totals.fats.toFixed(1)}).eq("id",selectedDiet.id);if(error)setError(error.message);else setSelectedDiet({...selectedDiet,daily_calories:totals.calories,protein_g:+totals.protein.toFixed(1),carbs_g:+totals.carbs.toFixed(1),fats_g:+totals.fats.toFixed(1)});}
  async function createTemplate(){if(!templateName.trim())return;setSaving(true);const {data:user}=await supabase.auth.getUser();if(!user.user){setError("Faça login como personal.");setSaving(false);return;}const {data,error}=await db.from("diet_templates").insert({personal_id:user.user.id,name:templateName.trim(),description:templateDesc.trim()||null}).select().single();if(error)setError(error.message);else{setTemplateOpen(false);setTemplateName("");setTemplateDesc("");await loadTemplates();if(data)await loadTemplate(data as Template);}setSaving(false);}
  async function saveDietAsTemplate(){if(!selectedDiet)return;setSaving(true);const {data:user}=await supabase.auth.getUser();if(!user.user){setError("Faça login como personal.");setSaving(false);return;}const {data:t,error}=await db.from("diet_templates").insert({personal_id:user.user.id,name:selectedDiet.name,description:selectedDiet.notes,daily_calories:totals.calories,protein_g:+totals.protein.toFixed(1),carbs_g:+totals.carbs.toFixed(1),fats_g:+totals.fats.toFixed(1)}).select().single();if(error||!t){setError(error?.message||"Não foi possível criar o modelo.");setSaving(false);return;}for(const m of meals){const {data:tm}=await db.from("diet_template_meals").insert({template_id:t.id,name:m.name,scheduled_time:m.scheduled_time,position:m.position,notes:m.notes}).select().single();for(const item of items[m.id]||[])await db.from("diet_template_items").insert({template_meal_id:tm.id,food_id:item.food_id,food_name:item.food_name,quantity:item.quantity,unit:item.unit,calories:item.calories,protein_g:item.protein_g,carbs_g:item.carbs_g,fats_g:item.fats_g,position:item.position});}await loadTemplates();setView("templates");setSelectedTemplate(t as Template);setSaving(false);}
  async function applyTemplate(t:Template){if(!selectedStudent)return;setSaving(true);const {data:user}=await supabase.auth.getUser();if(!user.user){setError("Faça login como personal.");setSaving(false);return;}const {data:d,error}=await supabase.from("diets").insert({student_id:selectedStudent,personal_id:user.user.id,name:t.name,notes:t.description,daily_calories:t.daily_calories||0,protein_g:t.protein_g||0,carbs_g:t.carbs_g||0,fats_g:t.fats_g||0}).select().single();if(error||!d){setError(error?.message||"Falha ao aplicar modelo.");setSaving(false);return;}const {data:ms}=await db.from("diet_template_meals").select("*").eq("template_id",t.id).order("position");for(const m of ms||[]){const {data:nm}=await supabase.from("meals").insert({diet_id:d.id,name:m.name,scheduled_time:m.scheduled_time,position:m.position,notes:m.notes}).select().single();const {data:its}=await db.from("diet_template_items").select("*").eq("template_meal_id",m.id).order("position");for(const item of its||[])await db.from("meal_items").insert({meal_id:nm?.id || "",food_id:item.food_id,food_name:item.food_name,quantity:item.quantity,unit:item.unit,calories:item.calories,protein_g:item.protein_g,carbs_g:item.carbs_g,fats_g:item.fats_g,position:item.position});}setView("diets");await loadDiets();await loadDiet(d as Diet);setSaving(false);}
  async function loadSubs(item:Item){const {data,error}=await db.from("food_substitutions").select("*").eq("meal_item_id",item.id).order("food_name");if(error)setError(error.message);else{setSubstitutions((data||[]) as Substitution[]);setEditingItem(item);setSubOpen(true);}}
  async function addSubstitution(){if(!editingItem||!subFoodId)return;const food=foods.find(f=>f.id===subFoodId);if(!food)return;const macros=calc(food,subQty);const {error}=await db.from("food_substitutions").insert({meal_item_id:editingItem.id,food_id:food.id,food_name:food.name,quantity:subQty,unit:"g",...macros});if(error)setError(error.message);else{setSubFoodId("");setSubQty(100);await loadSubs(editingItem);}}
  async function removeSub(id:string){const {error}=await db.from("food_substitutions").delete().eq("id",id);if(error)setError(error.message);else if(editingItem)await loadSubs(editingItem);}

  return <div>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.2em] text-primary">Nutrição</p><h1 className="text-3xl font-black uppercase leading-none md:text-4xl">Construtor de dieta</h1></div><div className="flex gap-2"><Button variant={view==="diets"?"default":"outline"} onClick={()=>setView("diets")}><Utensils/>Dietas</Button><Button variant={view==="templates"?"default":"outline"} onClick={()=>setView("templates")}><BookOpen/>Modelos</Button>{view==="diets"&&<Button onClick={()=>setDietOpen(true)} disabled={!selectedStudent}><Plus/>Nova dieta</Button>}{view==="templates"&&<Button onClick={()=>setTemplateOpen(true)}><Plus/>Novo modelo</Button>}</div></div>
    {error&&<div className="mb-4 border border-primary/50 bg-primary/10 p-3 text-sm">{error}</div>}
    {view==="diets"?<>
      <div className="mb-5 grid gap-3 lg:grid-cols-[1fr_2fr]"><div className="border border-border bg-card p-3"><p className="mb-2 text-[10px] font-bold uppercase text-muted-foreground">Aluno</p><Select value={selectedStudent} onValueChange={v=>{setSelectedStudent(v);setSelectedDiet(null);setMeals([]);setItems({});}}><SelectTrigger><SelectValue placeholder="Selecione um aluno"/></SelectTrigger><SelectContent>{students.map(s=><SelectItem key={s.id} value={s.id}>{s.full_name||"Aluno"}</SelectItem>)}</SelectContent></Select></div><div className="border border-border bg-card p-3"><p className="mb-2 text-[10px] font-bold uppercase text-muted-foreground">Totais</p><div className="flex flex-wrap gap-5 text-sm"><b>{totals.calories} kcal</b><span>{totals.protein.toFixed(1)}g P</span><span>{totals.carbs.toFixed(1)}g C</span><span>{totals.fats.toFixed(1)}g G</span></div></div></div>
      <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><div className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-3"><b className="text-xs uppercase">Histórico de dietas</b><span className="text-xs text-muted-foreground">{diets.length}</span></div>{diets.length?diets.map(d=><button key={d.id} onClick={()=>loadDiet(d)} className={cn("w-full border-b border-border p-3 text-left",selectedDiet?.id===d.id&&"border-l-2 border-l-primary bg-secondary")}><b>{d.name}</b><p className="mt-1 text-xs text-muted-foreground">{d.daily_calories||0} kcal · {d.protein_g||0}g P</p></button>):<div className="p-5 text-sm text-muted-foreground">Nenhuma dieta criada.</div>}</div>
      <div className="border border-border bg-card">{!selectedDiet?<div className="py-20 text-center"><Utensils className="mx-auto text-primary"/><p className="mt-3 font-bold">Selecione uma dieta</p></div>:<><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div><p className="text-[10px] font-bold uppercase tracking-widest text-primary">Plano alimentar</p><h2 className="mt-1 text-2xl font-black uppercase">{selectedDiet.name}</h2></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={saveDietAsTemplate} disabled={saving}><Copy/>Salvar modelo</Button><Button variant="outline" onClick={syncTotals}><Save/>Atualizar totais</Button><Button onClick={()=>setMealOpen(true)}><Plus/>Refeição</Button></div></div><div className="grid grid-cols-4 border-b border-border bg-secondary/50 text-center">{[["KCAL",totals.calories],["PROTEÍNA",`${totals.protein.toFixed(1)}g`],["CARBO",`${totals.carbs.toFixed(1)}g`],["GORDURA",`${totals.fats.toFixed(1)}g`]].map(([l,v])=><div key={String(l)} className="p-3"><b>{v}</b><span className="block text-[9px] font-bold text-muted-foreground">{l}</span></div>)}</div><div className="divide-y divide-border">{meals.map(meal=><section key={meal.id}><div className="flex items-center gap-3 p-4"><div className="flex-1"><b>{meal.name}</b><span className="ml-2 text-xs text-primary">{meal.scheduled_time?.slice(0,5)||"sem horário"}</span></div><Button size="sm" onClick={()=>{setSelectedMeal(meal);setFoodOpen(true)}}><Plus/>Alimento</Button><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem className="text-destructive" onClick={()=>removeMeal(meal)}><Trash2/>Excluir refeição</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>{(items[meal.id]||[]).map(item=><div key={item.id} className="flex items-center gap-3 border-t border-border px-4 py-3"><div className="flex-1"><b>{item.food_name}</b><p className="mt-1 text-xs text-muted-foreground">{item.quantity}{item.unit} · {item.calories||0} kcal · {item.protein_g||0}g P · {item.carbs_g||0}g C · {item.fats_g||0}g G</p></div><Button size="icon" variant="ghost" onClick={()=>{setEditingItem(item);setQuantity(item.quantity);setEditItemOpen(true)}}><MoreHorizontal/></Button></div>)}</section>)}</div></>}</div></div></>
      :<div className="grid gap-5 lg:grid-cols-[300px_1fr]"><div className="border border-border bg-card"><div className="border-b border-border p-3"><b className="text-xs uppercase">Modelos de dieta</b></div>{templates.length?templates.map(t=><button key={t.id} onClick={()=>loadTemplate(t)} className={cn("w-full border-b border-border p-4 text-left",selectedTemplate?.id===t.id&&"border-l-2 border-l-primary bg-secondary")}><b>{t.name}</b><p className="mt-1 text-xs text-muted-foreground">{t.daily_calories||0} kcal</p></button>):<div className="p-5 text-sm text-muted-foreground">Nenhum modelo ainda.</div>}</div><div className="border border-border bg-card p-5">{!selectedTemplate?<div className="py-16 text-center text-muted-foreground">Selecione um modelo.</div>:<><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-primary">Template</p><h2 className="text-2xl font-black uppercase">{selectedTemplate.name}</h2></div><Button onClick={()=>applyTemplate(selectedTemplate)} disabled={!selectedStudent||saving}><Copy/>Aplicar ao aluno</Button></div><p className="mt-2 text-sm text-muted-foreground">{selectedTemplate.description||"Modelo reutilizável de dieta."}</p><div className="mt-6 space-y-3">{templateMeals.map(m=><div key={m.id} className="border border-border p-4"><b>{m.name}</b>{(templateItems[m.id]||[]).map(i=><p key={i.id} className="mt-2 text-sm">{i.food_name} — {i.quantity}{i.unit}</p>)}</div>)}</div></>}</div></div>}

    <Dialog open={dietOpen} onOpenChange={setDietOpen}><DialogContent><DialogHeader><DialogTitle className="font-black uppercase">Nova dieta</DialogTitle></DialogHeader><div className="space-y-4"><label className="field">Nome<Input value={dietName} onChange={e=>setDietName(e.target.value)} placeholder="Ex.: Hipertrofia — 2.500 kcal"/></label><label className="field">Observações<Textarea value={dietNotes} onChange={e=>setDietNotes(e.target.value)}/></label></div><DialogFooter><Button variant="outline" onClick={()=>setDietOpen(false)}>Cancelar</Button><Button onClick={createDiet} disabled={saving||!dietName.trim()}><Save/>Criar dieta</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={templateOpen} onOpenChange={setTemplateOpen}><DialogContent><DialogHeader><DialogTitle className="font-black uppercase">Novo modelo de dieta</DialogTitle></DialogHeader><div className="space-y-4"><label className="field">Nome<Input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="Ex.: 2.500 kcal hipertrofia"/></label><label className="field">Descrição<Textarea value={templateDesc} onChange={e=>setTemplateDesc(e.target.value)}/></label></div><DialogFooter><Button variant="outline" onClick={()=>setTemplateOpen(false)}>Cancelar</Button><Button onClick={createTemplate} disabled={saving||!templateName.trim()}><Save/>Criar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={mealOpen} onOpenChange={setMealOpen}><DialogContent><DialogHeader><DialogTitle className="font-black uppercase">Nova refeição</DialogTitle></DialogHeader><div className="space-y-4"><label className="field">Nome<Input value={mealName} onChange={e=>setMealName(e.target.value)} placeholder="Café da manhã"/></label><label className="field">Horário<Input type="time" value={mealTime} onChange={e=>setMealTime(e.target.value)}/></label></div><DialogFooter><Button variant="outline" onClick={()=>setMealOpen(false)}>Cancelar</Button><Button onClick={createMeal} disabled={saving||!mealName.trim()}><Save/>Criar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={foodOpen} onOpenChange={setFoodOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle className="font-black uppercase">Adicionar alimento</DialogTitle><DialogDescription>Use os valores por 100g e informe a quantidade prescrita.</DialogDescription></DialogHeader><div className="space-y-4"><label className="field">Alimento salvo<select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={selectedFoodId} onChange={e=>chooseFood(e.target.value)}><option value="">Novo alimento</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="field">Nome<Input value={foodForm.name} onChange={e=>setFoodForm(f=>({...f,name:e.target.value}))}/></label><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{([["Kcal/100g","calories_per_100g"],["P/100g","protein_per_100g"],["C/100g","carbs_per_100g"],["G/100g","fats_per_100g"]] as const).map(([label,key])=><label className="field" key={key}>{label}<Input type="number" value={(foodForm as any)[key]} onChange={e=>setFoodForm(f=>({...f,[key]:Number(e.target.value)}))}/></label>)}</div><label className="field">Quantidade (g)<Input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label>{foodForm.name&&<div className="border border-border bg-secondary p-3 text-sm">{calc(foodForm,quantity).calories} kcal · {calc(foodForm,quantity).protein_g}g P · {calc(foodForm,quantity).carbs_g}g C · {calc(foodForm,quantity).fats_g}g G</div>}</div><DialogFooter><Button variant="outline" onClick={()=>{setFoodOpen(false);resetFood()}}><X/>Cancelar</Button><Button onClick={saveFoodAndAdd} disabled={saving||!foodForm.name.trim()||quantity<=0}><Save/>Adicionar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={editItemOpen} onOpenChange={setEditItemOpen}><DialogContent><DialogHeader><DialogTitle className="font-black uppercase">Editar quantidade</DialogTitle></DialogHeader><label className="field">Quantidade (g)<Input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><DialogFooter><Button variant="outline" onClick={()=>setEditItemOpen(false)}>Cancelar</Button><Button onClick={updateItem}><Save/>Salvar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={subOpen} onOpenChange={setSubOpen}><DialogContent><DialogHeader><DialogTitle className="font-black uppercase">Substituições</DialogTitle><DialogDescription>{editingItem?.food_name} — escolha alternativas cadastradas.</DialogDescription></DialogHeader><div className="space-y-3">{substitutions.map(s=><div key={s.id} className="flex items-center gap-3 border border-border p-3"><div className="flex-1"><b>{s.food_name}</b><p className="text-xs text-muted-foreground">{s.quantity}{s.unit} · {s.calories||0} kcal · {s.protein_g||0}g P</p></div><Button variant="ghost" size="icon" onClick={()=>removeSub(s.id)}><Trash2/></Button></div>)}<div className="grid gap-2 sm:grid-cols-[1fr_120px_auto]"><select className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={subFoodId} onChange={e=>setSubFoodId(e.target.value)}><option value="">Escolha alimento</option>{foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><Input type="number" value={subQty} onChange={e=>setSubQty(Number(e.target.value))}/><Button onClick={addSubstitution}><Plus/></Button></div></div><DialogFooter><Button onClick={()=>setSubOpen(false)}>Fechar</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
